# Generated by Django 5.1.5 on 2025-03-28 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField()),
                ('card_info', models.TextField()),
                ('price', models.TextField()),
                ('address', models.TextField()),
                ('time', models.TextField()),
                ('link', models.TextField()),
                ('formatted_time', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name_kz', models.TextField()),
                ('name_eng', models.TextField()),
                ('marker', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('district_id', models.BigIntegerField()),
                ('hexagon_id', models.BigIntegerField()),
                ('city_id', models.BigIntegerField()),
                ('sub_category_id', models.BigIntegerField()),
            ],
        ),
    ]
